# tell docker what version of the docker-compose.yml we're using
version: '3'

# define the network
networks:
  web-network:

# start the services section
services:
  # define the name of our service
  # corresponds to the "--name" parameter
  docker-php-cli:
    # define the directory where the build should happened,
    # i.e where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: ./php-cli
    # reserve a tty - otherwise the container shuts down immediately
    # corresponds to the "-i" flag
    tty: true
    # mount the api directory of the host to /var/www in the container
    # corresponds to the "-v" option
    volumes:
      - ./www:/var/www/html
    # connect to the network
    # corresponds to the "--network" option
    networks:
      - web-network

  docker-nginx:
    build:
      context: ./nginx
    # defines the port mapping
    # corresponds to the "--network" option
    networks:
      - web-network
    
  docker-nginx:
    build:
      context: ./nginx
    # defines the port mapping
    # corresponds to the "-p" flag
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-php-fpm:
    build:
      context: ./php-fpm
    tty: true
    volumes:
      - ./www:/var/www/html
    networks:
      - web-network

  docker-mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    networks: 
      - web-network
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER:   app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password