version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=mypassword
    ports:
      - "8082:3306"
  website:
    container_name: php72
    image: tut:php_img
    build:
      context: ./
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql