version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    ports:
      - "3307:3306"
  website:
    container_name: prestashop
    image: checkout.com/prestashop
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - mysql
