version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - "8082:3306"
  website:
    container_name: php72
    image: tut:php_img
    build:
      context: ./apache2
    volumes:
      - ./www:/var/www/html/
      - ./apache2/sites-available:/etc/apache2/sites-available
    ports:
      - 80:80
    depends_on:
      - mysql